// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDMbm-kK4yPEy0lsvv-hUBOBYIIwjohulM',
  //   appId: '1:757892127923:ios:dec53e361998a9df3f24c6',
  //   messagingSenderId: '757892127923',
  //   projectId: 'maths123-d732c',
  //   storageBucket: 'maths123-d732c.appspot.com',
  //   iosBundleId: 'com.example.kurupsApp',
  // );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwfuA20gDXMYLz7DK9ndtXq3YjBeQ9-c',
    appId: '1:757892127923:android:f8a31af3c38119133f24c6',
    messagingSenderId: '757892127923',
    projectId: 'maths123-d732c',
    storageBucket: 'maths123-d732c.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDFER_UX-rQ2WLRt9b4kkornvNywRgHdoI',
  //   appId: '1:197396646377:ios:5f725a97dccd856a06a378',
  //   messagingSenderId: '197396646377',
  //   projectId: 'batikair-my-prod',
  //   storageBucket: 'batikair-my-prod.appspot.com',
  //   iosBundleId: 'com.batikairmyios.app',
  // );
}
