// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDMbm-kK4yPEy0lsvv-hUBOBYIIwjohulM',
  //   appId: '1:757892127923:ios:dec53e361998a9df3f24c6',
  //   messagingSenderId: '757892127923',
  //   projectId: 'maths123-d732c',
  //   storageBucket: 'maths123-d732c.appspot.com',
  //   iosBundleId: 'com.example.kurupsApp',

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwfuA20gDXMYLz7DK9ndtXq3YjBeQ9-c',
    appId: '1:757892127923:android:595e2b047add78903f24c6',
    messagingSenderId: '757892127923',
    projectId: 'maths123-d732c',
    storageBucket: 'maths123-d732c.appspot.com',
  );

  // );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDMbm-kK4yPEy0lsvv-hUBOBYIIwjohulM',
      appId: '1:757892127923:ios:b56f913fe317c2ca3f24c6',
      messagingSenderId: '757892127923',
      projectId: 'maths123-d732c',
      storageBucket: 'maths123-d732c.appspot.com',
      iosBundleId: 'com.kurups.maths.ios');

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5R0WkSGsWHnrJP6ONVh2oCgkmAuU3gOw',
    appId: '1:757892127923:web:d4ceb7020c03bbaa3f24c6',
    messagingSenderId: '757892127923',
    projectId: 'maths123-d732c',
    authDomain: 'maths123-d732c.firebaseapp.com',
    storageBucket: 'maths123-d732c.appspot.com',
  );

//   {
//   apiKey: "AIzaSyC5R0WkSGsWHnrJP6ONVh2oCgkmAuU3gOw",
//   authDomain: "maths123-d732c.firebaseapp.com",
//   projectId: "maths123-d732c",
//   storageBucket: "maths123-d732c.appspot.com",
//   messagingSenderId: "757892127923",
//   appId: "1:757892127923:web:760d921242ee8c6d3f24c6"
// }
}
